# Generated by Django 5.2 on 2025-05-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('name_short', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enum', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='django_db_app.category')),
                ('measure', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='django_db_app.measure')),
            ],
        ),
        migrations.CreateModel(
            name='EnumValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('priority', models.SmallIntegerField(default=0)),
                ('value_str', models.CharField(blank=True, max_length=128, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_real', models.FloatField(blank=True, null=True)),
                ('value_path', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_db_app.category')),
            ],
            options={
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('real', 'Real'), ('enum', 'Enum'), ('path', 'Path')], max_length=4)),
                ('name', models.CharField(max_length=128)),
                ('name_short', models.CharField(max_length=8, unique=True)),
                ('min_val', models.IntegerField(blank=True, null=True)),
                ('max_val', models.IntegerField(blank=True, null=True)),
                ('enum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_db_app.category')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_db_app.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_db_app.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ParameterAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated', to='django_db_app.parameter')),
                ('parent_param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregates', to='django_db_app.parameter')),
            ],
            options={
                'unique_together': {('parent_param', 'param')},
            },
        ),
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=128, null=True)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_real', models.FloatField(blank=True, null=True)),
                ('value_path', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_db_app.category')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_db_app.parameter')),
                ('value_enum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_db_app.enumvalue')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_db_app.product')),
            ],
            options={
                'unique_together': {('param', 'category'), ('param', 'product')},
            },
        ),
    ]
